"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ValueString = exports.DefinePropertyString = exports.ObjectString = exports.GlobalString = void 0;
var GlobalString = "global";
exports.GlobalString = GlobalString;
var ObjectString = "Object";
exports.ObjectString = ObjectString;
var DefinePropertyString = "defineProperty";
exports.DefinePropertyString = DefinePropertyString;
var ValueString = "value";
exports.ValueString = ValueString;
